DROP TABLE IF EXISTS ProductCategories;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Categories;

CREATE TABLE Products(
    ProdKey VARCHAR(20) PRIMARY KEY NOT NULL,
    Name VARCHAR(20) NOT NULL,
);

CREATE TABLE Categories(
    CatKey VARCHAR(20) PRIMARY KEY NOT NULL,
    Name VARCHAR(20) NOT NULL,
);

CREATE TABLE ProductCategories(
    Id INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,

    ProdKey VARCHAR(20) FOREIGN KEY REFERENCES Products(ProdKey),
    CatKey VARCHAR(20) FOREIGN KEY REFERENCES Categories(CatKey),
);

